// <auto-generated />
using System;
using IdeaTree.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdeaTree.Migrations
{
    [DbContext(typeof(IdeaTreeContext))]
    [Migration("20190816060319_Mig2")]
    partial class Mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdeaTree.Models.Idea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<string>("Description");

                    b.Property<int?>("ModifiedByID");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<DateTime>("PostDate");

                    b.Property<int?>("PostedByID");

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("ID");

                    b.HasIndex("ModifiedByID");

                    b.HasIndex("PostedByID");

                    b.ToTable("Idea");
                });

            modelBuilder.Entity("IdeaTree.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Email");

                    b.Property<string>("Image");

                    b.Property<DateTime>("LastLogon");

                    b.Property<int>("MType");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Newsletter");

                    b.Property<string>("Password");

                    b.Property<DateTime?>("PasswordGenerateDate");

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("IdeaTree.Models.Idea", b =>
                {
                    b.HasOne("IdeaTree.Models.Member", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedByID");

                    b.HasOne("IdeaTree.Models.Member", "PostedBy")
                        .WithMany()
                        .HasForeignKey("PostedByID");
                });
#pragma warning restore 612, 618
        }
    }
}
